
package com.soap6.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceDocente", targetNamespace = "http://ws.soap6.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceDocente {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocente", targetNamespace = "http://ws.soap6.com/", className = "com.soap6.ws.GetDocente")
    @ResponseWrapper(localName = "getDocenteResponse", targetNamespace = "http://ws.soap6.com/", className = "com.soap6.ws.GetDocenteResponse")
    @Action(input = "http://ws.soap6.com/ServiceDocente/getDocenteRequest", output = "http://ws.soap6.com/ServiceDocente/getDocenteResponse")
    public String getDocente(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocentes", targetNamespace = "http://ws.soap6.com/", className = "com.soap6.ws.GetDocentes")
    @ResponseWrapper(localName = "getDocentesResponse", targetNamespace = "http://ws.soap6.com/", className = "com.soap6.ws.GetDocentesResponse")
    @Action(input = "http://ws.soap6.com/ServiceDocente/getDocentesRequest", output = "http://ws.soap6.com/ServiceDocente/getDocentesResponse")
    public List<String> getDocentes();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     */
    @WebMethod
    @RequestWrapper(localName = "addDocente", targetNamespace = "http://ws.soap6.com/", className = "com.soap6.ws.AddDocente")
    @ResponseWrapper(localName = "addDocenteResponse", targetNamespace = "http://ws.soap6.com/", className = "com.soap6.ws.AddDocenteResponse")
    @Action(input = "http://ws.soap6.com/ServiceDocente/addDocenteRequest", output = "http://ws.soap6.com/ServiceDocente/addDocenteResponse")
    public void addDocente(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6);

}
